default:
  image: ubuntu:22.04

stages:    
  - run

setup-job:
  stage: run
  script:
    - echo "Installing dependencies ..."
    - apt update && apt install -y meson ninja-build libgtest-dev
    - echo "Compiling the code..."
    - meson build
    - ninja -C build
    - echo "Running unit tests..."
    - build/test/fifo_test
    